- name: aesthetics setup
  become: true
  apt:
    name: ["nitrogen", "picom"]
  tags: &aesthetics_tags ["main", "aesthetics"]

- name: download all wallpapers
  git:
    repo: git@github.com:NoseferatuWKF/wallpapers.git
    dest: "{{ home }}/wallpapers"
  tags: *aesthetics_tags
