- name: docker deps
  become: true
  apt:
    force_apt_get: true
    name: ["ca-certificates", "curl", "gnupg", "lsb-release"]
  tags: &docker_tags ["main", "docker"]

- name: gpg
  become: true
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg"
  tags: *docker_tags

- name: apt repo
  become: true
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags: *docker_tags

- name: install finally
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
    state: latest
  tags: *docker_tags

- name: start docker
  become: true
  service:
    name: docker
    state: started
    enabled: yes
  tags: *docker_tags
