- name: install stow
  become: true
  apt: name=stow
  tags: &dotfiles_tags ["main", "dotfiles", "zsh", "nvim", "aesthetics", "etc"]

- name: clone repo
  git:
    repo: git@github.com:NoseferatuWKF/.dotfiles.git
    dest: "{{ home }}/.dotfiles"
    accept_hostkey: true
    version: master
    force: false
    update: false
  tags: [*dotfiles_tags, "repo"]

- name: stow
  shell: >
    cd {{ home }}/.dotfiles && \
    stow --adopt -v dunst git i3 nitrogen nvim picom pipewire pop tmux zsh && \
    git restore .
  tags: *dotfiles_tags
