- name: install stow
  apt: name=stow
  tags: &dotfile_tags ["main", "zsh", "nvim", "etc"]

- name: mac stow
  shell: "brew install stow"
  tags: mac

- name: clone repo
  git:
    repo: git@github.com:NoseferatuWKF/.dotfiles.git
    dest: "{{ home }}/.dotfiles"
    accept_hostkey: true
    version: master
    force: true
    update: true
  tags: [*dotfile_tags, "mac"]

- name: stow
  shell: "cd {{ home }}/.dotfiles && stow --adopt * && git checkout ."
  tags: [*dotfile_tags, "mac"]
