- name: install stow
  apt: name=stow
  tags: ["main", "zsh", "nvim", "etc"]

- name: clone repo
  git:
    repo: https://github.com/NoseferatuWKF/.dotfiles.git
    dest: "{{ home }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags: ["main", "zsh", "nvim", "etc"]

- name: stow
  shell: "cd {{ home }}/.dotfiles && stow --adopt * && git checkout ."
  tags: ["main", "zsh", "nvim", "etc"]
