- name: install stow
  become: true
  apt: name=stow
  tags: &dotfiles_tags ["main", "dotfiles", "zsh", "nvim", "aesthetics", "etc"]

- name: mac stow
  shell: "brew install stow"
  tags: ["brew", "mac"]

- name: clone repo
  git:
    repo: git@github.com:NoseferatuWKF/.dotfiles.git
    dest: "{{ home }}/.dotfiles"
    accept_hostkey: true
    version: master
    force: true
    update: true
  tags: [*dotfiles_tags, "mac"]

- name: stow
  shell: "cd {{ home }}/.dotfiles && stow --adopt * && git restore ."
  tags: [*dotfiles_tags, "mac"]
