- name: utils
  become: true
  apt:
    name: ["tmux", "tree", "ripgrep", "fzf", "htop", "i3", "rsync"]
  tags: ["main", "nvim", "etc"]

- name: mac utils
  become: true
  shell: "brew install tmux tree ripgrep fzf rsync xclip"
  tags: ["brew", "mac"]

