- name: utils
  become: true
  apt:
    name:
      - tmux
      - tree
      - ripgrep
      - fzf
      - htop
      - rsync
      - xclip
      - entr
      - flameshot
      - magic-wormhole
  tags: ["main", "nvim", "tmux", "utils", "etc"]

- name: tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ home }}/.tmux/plugins/tpm"
  tags: ["main", "tmux", "tpm", "etc"]

- name: create font dir
  file:
    path: "{{ home }}/.local/share/fonts"
    state: directory
  tags: &fonts_tags ["main", "fonts", "nvim", "tmux"]

- name: install Hack Bold
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/HackNerdFont-Bold.ttf
    dest: "{{ home }}/.local/share/fonts/Hack Bold Nerd Font Complete.ttf"
  tags: *fonts_tags

- name: install Hack BoldItalic
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/HackNerdFont-BoldItalic.ttf
    dest: "{{ home }}/.local/share/fonts/Hack BoldItalic Nerd Font Complete.ttf"
  tags: *fonts_tags

- name: install Hack Italic
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/HackNerdFont-Italic.ttf
    dest: "{{ home }}/.local/share/fonts/Hack Italic Nerd Font Complete.ttf"
  tags: *fonts_tags

- name: install Hack Regular
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/HackNerdFont-Regular.ttf
    dest: "{{ home }}/.local/share/fonts/Hack Regular Nerd Font Complete.ttf"
  tags: *fonts_tags

- name: gh cli
  become: true
  shell: >
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
    gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
    tee /etc/apt/sources.list.d/github-cli.list > /dev/null && apt update && apt install -y gh
  tags: ["main", "gh", "etc"]
