- name: gpg
  become: true
  shell: >
    curl -fsSL https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2023.02.18_all.deb 
    -o {{ home }}/i3.deb && apt install {{ home }}/i3.deb 
  tags: &i3_tags ["main", "i3"]

- name: apt repo
  become: true
  shell: >
    echo "deb [arch=$(dpkg --print-architecture)] http://debian.sur5r.net/i3/ $(lsb_release -cs) universe" | 
    sudo tee /etc/apt/sources.list.d/sur5r-i3.list
  tags: *i3_tags

- name: install i3
  become: true
  apt:
    update_cache: true
    name: i3
  tags: *i3_tags

- name: cleanup
  file:
    path: "{{ home }}/i3.deb"
    state: absent
  tags: *i3_tags
