- name: nvim deps
  become: true
  apt:
    force_apt_get: true
    name: ["ninja-build", "gettext", "cmake", "g++", "pkg-config", "unzip", "doxygen"]
  tags: &nvim_tags ["main", "nvim"]

- name: clone
  git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ home }}/neovim"
    force: true
  tags: *nvim_tags

- name: build & install
  become: true
  shell: >
    cd {{ home }}/neovim && \
    make CMAKE_BUILD_TYPE=RelWithDebInfo && make install
  tags: *nvim_tags
