- name: install zsh
  become: true
  apt: name=zsh
  tags: &zsh_tags ["main", "zsh"]

- name: change shell
  become: true
  shell: "chsh -s $(which zsh) {{ lookup('env', 'USER') }}"
  tags: *zsh_tags

- name: install antibody
  become: true
  shell: curl -sfL git.io/antibody | sh -s - -b /usr/local/bin
  tags: *zsh_tags
